### ISSUE TITLE
[French] Kronorium translations

### ISSUE THREAD

**Issue by zeroy99** [dtzxporter/Kronorium#18]
Almost completed. [ZeRoY]

**Comment by BridouxT** [comment]
What have you already done ? We could maybe put in in common ?

**Comment by yriou** [comment]
line 857 - Half way or more, you want to start from the bottom and work way up?

**Comment by zeroy99** [comment]
line 857 - Half way or more, you want to start from the bottom and work way up?

**Comment by samoht2000** [comment]
Yes, I'll made the bios of the character now and I'll go to the top

**Comment by BridouxT** [comment]
Here are the bios, you're more advanced than me and seems to be faster so I let the rest upon you. ( It's been a couple of hours I'm working on it so I'm taking a rest) http://www.jsoneditoronline.org/?id=bd26369f734c65efa8fd53d498468214

**Comment by Schwarzenigga** [comment]
I'm already working on it with a friend maybe we can share our work. I made it from the pdf transcription what peoples shared on reddit. I personally translated the 15th first pages and my friend started the dimension 63 's section. I maybe can start another section to help.

**Comment by zeroy99** [comment]
I am already in Dimension 63, will have the all thing done by tomorrow...

**Comment by BridouxT** [comment]
For your information, "Resolution 1295" is translated by "Décision 1295" in BO2 (Proof : http://fr.callofduty.wikia.com/wiki/Buried ) + I personnally think that "Ether Corrompu" would be a better translation than "Ether Sombre" + you don't put "les" before Primis because it's a proper noun + "Wave Gun" is not translated in the game + "conduit" ---> " intermédiaire" in this situation

**Comment by zeroy99** [comment]
ok thanks

**Comment by zeroy99** [comment]
This is now fully done.

**Comment by dtzxporter** [comment]
*Marking as open till lands* Currently in layout phase!

**Comment by dtzxporter** [comment]
Closing because the commit landed

**Comment by bastien27** [comment]
@yriou c'est toi qui a traduit en français, tu n'a pas relus ?
regarde le stream de kenshin tu comprendra,
avec un autre utilisateur on va faire une re-lecture et poster la correction ;)

**Comment by zeroy99** [comment]
Il est tout a fait possible qu'il y est des erreurs mon ami :)

**Comment by bastien27** [comment]
bah c'est plus que possible, c'est mot pour mot du google trad'.
y'a une correction toutes les 2 phrases.
la correction sera poster ce soir

**Comment by bastien27** [comment]
Sa y est correction complète dans un BON français fini voir Pull Request #42 et #43
