### ISSUE TITLE
"Mob Of the Dead" Excerpt is placed in the wrong location

### ISSUE THREAD

**Issue by nmwood** [dtzxporter/Kronorium#26]
The following Excerpt is placed in the wrong order in the timeline

"MOB OF THE DEAD
Sal, Finn, Billy and Al battle waves of undead as they find themselves trapped in a seemingly endless cycle."

It is currently in between "DECEMBER 31ST, 1933 Finn, Sal and Billy lure Al to the roof and kill him." and "JANUARY 11TH, 1934 Stepping through a rift, Richtofen secures the blood samples of Sal and Finn."

This excerpt should be after 

"JANUARY 19TH, 1934
Found guilty of Al’s murder, Sal, Finn and Billy are executed by electric chair."

You can check the Timeline but I am 100% sure that it is in the wrong order.

**Comment by dtzxporter** [comment]
Fixed in upcoming commit.
