### ISSUE TITLE
"April 26th 1944" is missing in the Dimension 63 Timeline.

### ISSUE THREAD

**Issue by nmwood** [dtzxporter/Kronorium#27]
So Dimension 63 ends with "April 25th, 1944 - Shadows Of Evil...." but it should end with "April 26th 1944 The Apothicons destroy Dimension 63". That excerpt is completely missing. 

Here is an Imgur Album with proof http://imgur.com/a/u7iV2

It shows the last page of Dimension 63 and the page right after. "April 26th 1944..." is completely missing. The other two photos shows that the missing quote belong at the end of Dimension 63.

**Comment by dtzxporter** [comment]
Fixed in upcoming commit.
