### ISSUE TITLE
Inccorect Dimension number in "The Arrival of Eddie"

### ISSUE THREAD

**Issue by nmwood** [dtzxporter/Kronorium#28]
This transcription says "The Arrival of Edward - Richtofen collects Eddies innocent soul from Dimension 63, and Monty gives him a physical form in the House."

when it should say "The Arrival of Edward - Richtofen collects Eddies innocent soul from Dimension 2210, and Monty gives him a physical form in the House."

The number of the Dimension is wrong. This transcription says "63" when it is actually "2210"

Proof: http://imgur.com/a/7Byk7

**Comment by dtzxporter** [comment]
Fixed in upcoming commit.
