### ISSUE TITLE
The Entire "Fracture" Timeline part is incorrect. 

### ISSUE THREAD

**Issue by nmwood** [dtzxporter/Kronorium#29]
There are 3 DISTINCT timelines in the Fracture. Deceptio Fracture, Proditone Fracture and Agnoia Fracture. These are all SEPARATE universes and separate fractures. I see that the entire fracture part on this is just combined in order of the dates. But this is not accurate and gives a incorrect view of the fractures. It mixes up events that occur in multiple fractures. 

From this Timeline it seems Zetsubo, Gorod. and Der Eisendrache all occur in the same Fractured Universe. BUT this is not true they are all in SEPARATE fractures. 

You need 3 different sections Deceptio, Proditone and Agnoia. I am not making this up this is how it's OFFICIALLY laid out on the actual Timeline.  

This Transcription of the Timeline correctly lays out the fractures: https://drive.google.com/file/d/0BxfDEHDmRqPCMmJkV1hYQmdpbW8/view

**Comment by dtzxporter** [comment]
#26 #27 #28 Going to squash these now, referencing them here for reference.

**Comment by dtzxporter** [comment]
Awesome, yeah the original transcriptions were a mess. Refactoring this segment now.

EDIT: Fixed in upcoming commit.
