### ISSUE TITLE
Error found.

### ISSUE THREAD

**Issue by Plexiiar** [dtzxporter/Kronorium#34]
OCTOBER 13TH 1945
Samantha is teleported to the moon while Groph and Schuster work on the MPD. Running into the MPD, she is drawn inside of it, where she becomes corrupted by the Dark Aether. Maxis is teleported to the Crazy Place and develops the power to merge with electricity. Richtofen returns to the moon. Learning Samantha is trapped in the MPD, he orders Groph to teleport Maxis there to coax her out of the device. He also warns Groph to keep an eye out for an "evil looking dog." Richtofen returns to the moon. Learning Samantha is trapped in the MPD, he orders Groph to teleport Maxis there to coax her out of the device. He also warns Groph to keep an eye out for an "evil looking dog."

As you can see the paragraph "earning Samantha is trapped in the MPD, he orders Groph to teleport Maxis there to coax her out of the device. He also warns Groph to keep an eye out for an "evil looking dog." reads twice.

**Comment by dtzxporter** [comment]
Thanks, will have this fixed in a sec!

**Comment by dtzxporter** [comment]
Fixed thanks!
