### ISSUE TITLE
Miss-typed section

### ISSUE THREAD

**Issue by Meanbarrel** [dtzxporter/Kronorium#38]
On page 9  it reads:

"JANUARY 4TH, 1940
Richtofen and Schuster conduct their first human teleportation test Richtofen is so confident in its success, he volunteers the MPD, the Aether Pyramid hidden by the Apothicons. While inspecting the device Richtofen is electrocuted and begins hearing the many voices of corruption including that of the Shadowman. The device then teleports him to Shangri-La. Corrupted by the Dark Aether, Richtofen is gradually being driven insane by an obsession find Agartha."

it should read:

January 4th, 1940
Richtofen and Schuster conduct their first human teleportation test. Richtofen is so confident in its success, he volunteers **himself. Teleported to the Moon, he encountered** the MPD, the Aether Pyramid hidden by the Apothicons. While inspecting the device, Richtofen is electrocuted and begins hearing the many voices of corruption, including that of the Shadowman. The device then teleports him to Shangri-La. Corrupted by the Dark Aether, Richtofen is gradually being driven insane by an obsession to find Agartha."

the bolded words are missing from the master copy

**Comment by dtzxporter** [comment]
Awesome, will have this fixed in a moment, thanks!
